### ISSUE TITLE
Build a event scrapping API from BookMyShow based upon choice. See comments of this thread for details

### ISSUE THREAD

**Issue by dipan29** [mindwebs/API-WareHouse#2]
Check ReadME for more. Option #2

**Comment by SuranjanDaw** [comment]
List of APIs for respective topics are:
1. BookMyShow Tech events
2. BookMyShow Art event
3. BookMyShow Tavel event

Follow the format in the repo

Make a different folder if you find an existing API in one language and you want to code the same in a different language.

you can write code in PHP, nodejs or python.
